version: "4.34.3"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hombreshop
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: hombreshop
      MYSQL_USER: regular_user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: